language: ruby
rvm:
  - 2.4.1
env:
  - DB=pgsql
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
